# Permalinks
permalink:        pretty

# Setup
title:            React.careers
tagline:          Blogging on React & JavaScript
url:              http://react.careers/
paginate:         100
author:
  name:           Stefan Ritter
  url:            http://stefanritter.com
  email:          stefan@stefanritter.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/stefanRitter/jspadawan.com

sass:
  sass_dir:       _sass
  style:          :compressed

gems:
  - jekyll-sitemap
