# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            JS Padawan
tagline:          A JavaScript Blog
url:              http://jspadawan.com
paginate:         10
author:
  name:           Stefan Ritter
  url:            http://stefanritter.com
  email:          stefan@stefanritter.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/stefanRitter/jspadawan.com

sass:
  sass_dir:       _sass
  style:          :compressed

gems:
  - jekyll-sitemap
